# Generated by Django 6.0.3 on 2026-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Sci-Fi', 'Sci-Fi'), ('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Biography', 'Biography'), ('History', 'History'), ('Romance', 'Romance'), ('Classic', 'Classic'), ('Mystery', 'Mystery'), ('Self-Help', 'Self-Help'), ('Finance', 'Finance')], max_length=50),
        ),
    ]
